### ISSUE TITLE
Unable to run website locally

### ISSUE THREAD

**Issue by lunchboxav** [envoyproxy/envoy-website#221]
Hi all. I was trying to run website locally without Docker and it failed. I use Ruby 3.0.3 and it doesn't work. Seems like the issue comes from Jekyll itself based on this issue https://github.com/jekyll/jekyll/issues/8523

So, to solve this, I install `webrick` manually via `bundle add webrick` and now the local website is able to run locally.

Do I need to add this information in the README so anyone who faces this issue can solve it? Or are we planning to explicitly add webrick in Gemfile?

**Comment by phlax** [comment]
hi @lunchboxav thanks for raising this

im not too sure exactly how the website is currently put together, my inclination is to replace it with something js/react

what i do know is that netlify builds the site currently from the repo config, and `jekyll build`

if you are having trouble getting it to build, i would in the first instance look at the versions that are being used - eg https://github.com/envoyproxy/envoyproxy.github.io/blob/main/.ruby-version

**Comment by lunchboxav** [comment]
Ah yes thanks for the reply @phlax. I did experience an issue but I found the solution. And yeah, I use Ruby 3.0.3, and the README only mentions using Ruby version 2.1.0 up. 

Do you think it's better if I add a note in the README as a solution for this? In case somebody else has the same environment and face similar issue.

**Comment by phlax** [comment]
> Do you think it's better if I add a note in the README

yep, i think that would be helpful

incidentally there is a netlify way of building where you reproduce ci - not sure if you need a netlify account to do that tho

**Comment by phlax** [comment]
as an update to this, i am adding a bazel workspace to this repo #235 

this will make it much easier to manage versions, and have reproducible builds

with the new setup you will only need bazel to build the site locally, and builds will be hermetic etc

wrt the ruby version, it will be set to `2.7.2` as this is the version that comes by default with netlify so speeds up CI

if that version of ruby is not available on your host/env, it will compile ruby - which can be slow, but it only needs to do it once. Having the correct version avoids the need to do this.

i will update the README docs after i land this, it seems there are quite a few things out of date

**Comment by phlax** [comment]
this should be resolved now - README is updated with new way/s of running/developing the site locally
