### ISSUE TITLE
Production build no longer has Google Analytics enabled

### ISSUE THREAD

**Issue by chalin** [envoyproxy/envoy-website#274]
Visit the https://www.envoyproxy.io website and look at the **page source** of any page.

What would I expect to see? Scripts setting up UA GA using site ID `UA-148359966-1`, but there are none.

This is a prerequisite to #273.

/cc @caniszczyk

**Comment by phlax** [comment]
i rebuilt the site build ~recently to use bazel - not sure if i broke this at that time

**Comment by chalin** [comment]
Yeah, I think it happened at that time. It seems that bazel needs to be explicitly told which environment variables to pass along. See #275, thanks.

**Comment by phlax** [comment]
im wondering if fixing this will give us sight in the docs area which makes up a lot of the web site - if not i can look at resolving - perhaps we can do something with netlify (if that is not the case already)

**Comment by chalin** [comment]
Analytics are back!

```console
$ curl -i https://www.envoyproxy.io/ 2>/dev/null | grep UA-1
  ga('create', 'UA-148359966-1', 'auto');
```

**Comment by phlax** [comment]
not for docs it seems

```console
curl -i https://www.envoyproxy.io/docs/envoy/latest/ 2>/dev/null | grep UA-1
```

**Comment by phlax** [comment]
might be easier to switch to netlify snippet injection - im guessing we are using jekyll currently - i havent tried the netlify thing - but im guessing its pretty straight forward

**Comment by chalin** [comment]
You're right, snippet injection _would_ be a much simpler solution in this case! I'm going to add that as a comment to #273 so that we can continue tracking this thread there.

**Comment by chalin** [comment]
> im wondering if fixing this will give us sight in the docs area which makes up a lot of the web site

I'm unsure what kind of insights you're looking for, so I can't say if it will help. Good luck with whatever you are trying to resolve.
