### ISSUE TITLE
Wrong download link on envoyproxy.io

### ISSUE THREAD

**Issue by murphy85** [envoyproxy/envoy-website#296]
On [envoyproxy.io](https://www.envoyproxy.io/) there are two download buttons.

Top: https://www.envoyproxy.io/docs/envoy/latest/install/building
![screenshot_2492](https://user-images.githubusercontent.com/15668784/224948649-5b8e1ae2-f462-427b-a903-d0b376a2adb2.png)

Bottom: https://www.envoyproxy.io/docs/envoy/latest/start/install
![screenshot_2493](https://user-images.githubusercontent.com/15668784/224948739-e86dd1fe-ee17-45a9-9c65-ec51c54741ae.png)

The first one does not work, it shows 404

**Comment by phlax** [comment]
thanks for raising this @murphy85 - that button/link is wrong on quite a few levels 8/

if you fancy PRing to fix im happy to review, otherwise i will look at this asap

**Comment by murphy85** [comment]
Hi, thank you!
Unfortunately I couldn't find the source code of the envoyproxy website in git and didn't found "install/building" within a file in git.

**Comment by phlax** [comment]
see here for buttons

https://github.com/envoyproxy/envoy-website/blob/93f28a328ceac8423fe2a32c984e0423247ced6d/index.html#L20-L23

not sure exactly the best fix - i think download should not be pointing to the building page in the docs - i think that was the case for legacy reasons and i think the link is gone/moved now

**Comment by murphy85** [comment]
Probably using the same link for both, because the buttons look the same and have the same description and are both next to Get started?
But it's up to you which url you want to use :-)

**Comment by murphy85** [comment]
Here are the other buttons:
https://github.com/envoyproxy/envoy-website/blob/93f28a328ceac8423fe2a32c984e0423247ced6d/index.html#L112-L115
Maybe just copy them

**Comment by ishaanbahal** [comment]
Don't know if the fix above is right or wrong, but at least the link at the bottom goes somewhere, wanted to download envoy, the 404 doesn't look great for such an amazing project. 

Ref: https://github.com/envoyproxy/envoy-website/pull/305

**Comment by phlax** [comment]
hi @ishaanbahal it needs to be fixed in the envoy repo

i thought we had done this already if you want to PR there i can help otherwise i can clear this up

**Comment by phlax** [comment]
fixed in #305
