### ISSUE TITLE
Add documentation for a secure unit file with the envoy proxy edge installation

### ISSUE THREAD

**Issue by cccsss01** [envoyproxy/envoy-website#373]
It would be really helpful with a secure unit file for the edge proxy.  I'm assuming it needs one as I haven't seen much information on it.

**Comment by phlax** [comment]
im not sure what a secure unit file is - but im pretty sure if we do need one it wouldnt be added here

closing this - but feel free to follow up in the main envoy repo if you think this is still an issue - in that case please provide more information
